services:
  api:
    image: seravo-api
    build: .
    environment:
      - PYTHONPATH=/app
    healthcheck:
      disable: true
    ports: ["8080:8000"]
    volumes:
      - "./seravo/:/app/seravo:rw"
