name: "Lint Python code"
on: [push, pull_request]

jobs:
  lint-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.10"]
    steps:
      - name: Setup repository
        uses: actions/checkout@v3

      - name: Set up python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install essential tools
        run: pip install flake8

      - name: Run flake8
        run: flake8
